version: "3"

services:
  mgmt-frontend-service:
    tty: true
    build:
      context: ./../front-end
      dockerfile: ./../front-end/dockerfile
    depends_on:
      - mgmt-broker-service
    ports:
      - "80:80"

  mgmt-broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    depends_on:
      - postgres
    environment:
      NOTES_SERVICE_SERVICE_HOST: "mgmt-notes-service"
      AUTHENTICATION_SERVICE_SERVICE_HOST: "mgmt-authentication-service"
      PROJECT_SERVICE_SERVICE_HOST: "mgmt-project-service"
      EXTERNAL_COMPANY_SERVICE_SERVICE_HOST: "mgmt-external-company-service"
      ECONOMICS_SERVICE_SERVICE_HOST: "mgmt-economics-service"
      INVOICE_SERVICE_SERVICE_HOST: "mgmt-invoice-service"
      PRODUCT_SERVICE_SERVICE_HOST: "mgmt-product-service"

  mgmt-authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    depends_on:
      - postgres
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=auth sslmode=disable timezone=UTC connect_timeout=5"

  mgmt-project-service:
    build:
      context: ./../project-service
      dockerfile: ./../project-service/project-service.dockerfile
    environment:
      AUTHENTICATION_SERVICE_SERVICE_HOST: "mgmt-authentication-service"
      DSN: "host=postgres port=5432 user=postgres password=password dbname=projects sslmode=disable timezone=UTC connect_timeout=5"

  mgmt-notes-service:
    build:
      context: ./../notes-service
      dockerfile: ./../notes-service/notes-service.dockerfile
    depends_on:
      - postgres
    environment:
      INVOICE_SERVICE_SERVICE_HOST: "mgmt-invoice-service"
      PRODUCT_SERVICE_SERVICE_HOST: "mgmt-product-service"
      PROJECT_SERVICE_SERVICE_HOST: "mgmt-project-service"
      AUTHENTICATION_SERVICE_SERVICE_HOST: "mgmt-authentication-service"
      DSN: "host=postgres port=5432 user=postgres password=password dbname=notes sslmode=disable timezone=UTC connect_timeout=5"

  mgmt-economics-service:
    build:
      context: ./../economics-service
      dockerfile: ./../economics-service/economics-service.dockerfile
    depends_on:
      - postgres
    environment:
      AUTHENTICATION_SERVICE_SERVICE_HOST: "mgmt-authentication-service"
      DSN: "host=postgres port=5432 user=postgres password=password dbname=economics sslmode=disable timezone=UTC connect_timeout=5"

  mgmt-external-company-service:
    build:
      context: ./../external-company-service
      dockerfile: ./../external-company-service/external-company-service.dockerfile
    depends_on:
      - postgres
    environment:
      AUTHENTICATION_SERVICE_SERVICE_HOST: "mgmt-authentication-service"
      DSN: "host=postgres port=5432 user=postgres password=password dbname=companies sslmode=disable timezone=UTC connect_timeout=5"

  mgmt-product-service:
    build:
      context: ./../product-service
      dockerfile: ./../product-service/product-service.dockerfile
    depends_on:
      - postgres
    environment:
      AUTHENTICATION_SERVICE_SERVICE_HOST: "mgmt-authentication-service"
      DSN: "host=postgres port=5432 user=postgres password=password dbname=products sslmode=disable timezone=UTC connect_timeout=5"

  mgmt-invoice-service:
    build:
      context: ./../invoice-service
      dockerfile: ./../invoice-service/invoice-service.dockerfile
    depends_on:
      - postgres
    environment:
      EXTERNAL_COMPANY_SERVICE_SERVICE_HOST: "mgmt-external-company-service"
      ECONOMICS_SERVICE_SERVICE_HOST: "mgmt-economics-service"
      AUTHENTICATION_SERVICE_SERVICE_HOST: "mgmt-authentication-service"
      DSN: "host=postgres port=5432 user=postgres password=password dbname=invoice sslmode=disable timezone=UTC connect_timeout=5"

  postgres:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: management
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
