version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.12.4-alpine
    ports:
      - "5672:5672"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/
