export enum PRIVILEGES {
    user_read = 'user_read',
    user_write = 'user_write',
    user_sudo = 'user_sudo',
    privilege_read = 'privilege_read',
    privilege_write = 'privilege_write',
    privilege_sudo = 'privilege_sudo',
    project_read = 'project_read',
    project_write = 'project_write',
    project_sudo = 'project_sudo',
    sub_project_read = 'sub_project_read',
    sub_project_write = 'sub_project_write',
    sub_project_sudo = 'sub_project_sudo',
    external_company_read = 'external_company_read',
    external_company_write = 'external_company_write',
    external_company_sudo = 'external_company_sudo',
    note_read = 'note_read',
    note_write = 'note_write',
    note_sudo = 'note_sudo',
    economics_read = 'economics_read',
    economics_write = 'economics_write',
    economics_sudo = 'economics_sudo',
}